### ISSUE TITLE
Recyclerview item click listener

### ISSUE THREAD

**Issue by PeriyaCC** [vipafattal/KotlinRecycler#1]
Thanks for the awesome lib. Can you add recyclerview item click listener in the same style?

**Comment by vipafattal** [comment]
You can add a click listener on an item in this way:
```kotlin
        recyclerView.withSimpleAdapter(dummyData, R.layout.item_recipe) { data ->
            itemView.recipe_img.setImageResource(data.drawable)
            itemView.recipe_name.text = data.name
	    itemView.setOnClickListener {
	     //Do what you want when user click on item.
	    }
        }
```

**Comment by PeriyaCC** [comment]
Thanks for your quick response. Awesome!

**Comment by vipafattal** [comment]
most welcome

**Comment by PeriyaCC** [comment]
But itemView.setOnClickListener sets everytime on inflating view for each item. Any other method?

**Comment by vipafattal** [comment]
for now, if you want to avoid object creation you can create an interface of View.OnClickListener that pass it to 
```kotlin
itemView.setOnClickListener(your_click_interface)
```
in this way, the same instance will be called when the user clicks on an item.

I will work on it to make it easier and I will keep you updated.

**Comment by PeriyaCC** [comment]
Sound great.. ! Waiting for it, Thx

**Comment by vipafattal** [comment]
Closing feature request added on Version 1.2.1, see [readme](https://github.com/vipafattal/KotlinRecycler/blob/master/README.md) for how to implement on item click listener.
